# Etapa de build
FROM node:16 as build

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos de configuração
COPY package*.json ./
RUN npm install
COPY . .

# Compila o TypeScript para JavaScript
RUN npm run build

# Etapa de produção
FROM node:16

WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

# Porta onde a API irá rodar
EXPOSE 3000

# Comando para iniciar a API
CMD ["node", "dist/index.js"]
