# Etapa de build
FROM node:20.18.0 AS build

WORKDIR /src
RUN pwd
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20.18.0

WORKDIR /src
COPY --from=build /src/dist ./dist
COPY --from=build /src/node_modules ./node_modules

EXPOSE 3000
CMD ["node", "dist/server.js"]
